HopeForOrphans/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from HopeForOrphans import settings
from home import views as home_views
from django.contrib.auth import views as auth_views

from home.forms import MyAuthForm, MyPasswordResetForm, MySetPasswordForm, MyPasswordChangeForm

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', include('index.urls')),
    path('home/', include('home.urls')),
    path('signup/', home_views.signup, name='signup'),
    path('login/', home_views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt',
        form_class=MyPasswordResetForm,
    ), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        form_class=MySetPasswordForm,
    ),name='password_reset_confirm'
    ),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ),name='password_reset_complete'),
    path('settings/password/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change.html',
        form_class=MyPasswordChangeForm,
    ),name='password_change'),
    path('settings/password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html',
    ), name='password_change_done'),
]
#
# urlpatterns += [
#     path('', RedirectView.as_view(url='/home/', permanent=True))
# ]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('profile', views.orphanage_profile,name='profile'),
    path('my-orphans', views.my_orphans, name='my-orphans'),
    path('add-orphan', views.add_orphan, name='add-orphan'),
    path('orphan/<int:pk>', views.orphan_detail, name='orphan-detail'),
    path('edit-profile', views.edit_profile, name='edit-profile'),

    path('ajax/add_income_src', views.add_income_src, name='add-income-src'),
    path('ajax/add_facility', views.add_facility, name='add-facility'),
    path('ajax/delete-orphan', views.delete_orphan, name='delete-orphan'),

    path('edit-orphan/<int:pk>', views.edit_orphan, name='edit-orphan'),
    path('adoption-requests', views.adoption_requests, name='adoption-requests'),
    path('donations', views.donations, name='donations'),

    path('ajax/adoption_approval', views.adoption_approval, name='adopt-approval')

]

home/models.py
import uuid
from datetime import datetime, date

from django.db import models
from django.urls import reverse

from HopeForOrphans import settings


# Create your models here.

class Hobby(models.Model):
    name = models.CharField(max_length=64, help_text='Enter a hobby (e.g. cricket, football, gardening)')

    def __str__(self):
        """String for representing the model object"""
        return self.name


class Orphan(models.Model):
    first_name = models.CharField(max_length=64, help_text='First Name')
    last_name = models.CharField(max_length=64, help_text='Last Name')

    dob = models.DateField(help_text='Date of Birth')

    @property
    def calculate_age(self):
        if self.dob:
            return int((datetime.now().year - self.dob.year))

    # age = calculate_age()

    GENDER_CHOICE = (
        ('m', 'Male'),
        ('f', 'Female')
    )

    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICE,
        help_text='Gender',
        default='m',
    )

    orphanage = models.ForeignKey('Orphanage', on_delete=models.CASCADE)

    ADOPTION_STATUS = (
        ('a', 'Available'),
        ('n', 'Not Available'),
        ('u', 'Unknown'),
    )

    status = models.CharField(
        max_length=1,
        choices=ADOPTION_STATUS,
        help_text='Adoption Status',
        default='a'
    )

    date_joined = models.DateField(null=True, blank=True)

    def display_hobbies(self):
        return ', '.join(hobby.name for hobby in self.hobbies.all()[:3])

    hobbies = models.ManyToManyField(Hobby, help_text='Select hobbies', blank=True)

    education = models.CharField(max_length=64, blank=True, help_text='Education')

    avatar = models.ImageField(upload_to='orphans_dp/', null=True, blank=True)

    def __str__(self):
        return '{0} {1}, {2}'.format(self.first_name, self.last_name, self.dob)

    def get_absolute_url(self):
        return reverse('orphan-detail', args=[str(self.id)])

    class Meta:
        ordering = ['first_name', 'last_name']


def uploaded_dir_orphans(instance, filename):
    return 'user_{0}/{1}'.format(instance.orphan.orphanage.user.id, filename)


def uploaded_dir(instance, filename):
    return 'user_{0}/{1}'.format(instance.orphanage.user.id, filename)


class OrphansImages(models.Model):
    image = models.ImageField(upload_to=uploaded_dir_orphans, null=True, blank=True,
                              help_text='Upload an image')

    orphan = models.ForeignKey('Orphan', on_delete=models.CASCADE)


class OrphanagesImages(models.Model):
    image = models.ImageField(upload_to=uploaded_dir, null=True, blank=True,
                              help_text='Upload an image')

    orphanage = models.ForeignKey('Orphanage', on_delete=models.CASCADE)


class BankDetail(models.Model): #PayU Money gateway
    # account_num = models.IntegerField(help_text='16 digit account number')
    # bank_name = models.CharField(max_length=128, help_text='Bank name')
    # ifsc_code = models.CharField(max_length=64, help_text='IFSC code of bank branch')

    merchant_key = models.CharField(max_length=64, help_text='Merchant Key from PayU Money')
    merchant_salt = models.CharField(max_length=64, help_text='Merchant Salt from PayU Money')

    def __str__(self):
        return '{0}: {1}'.format(self.merchant_key, self.merchant_salt)


class Address(models.Model):
    locality = models.CharField(max_length=64, help_text='Locality')
    city = models.CharField(max_length=64, help_text='City')
    state = models.CharField(max_length=64, help_text='State') #choices
    zip_pin_code = models.CharField(max_length=12, help_text='Zip/Pin code')
    country = models.CharField(max_length=64, help_text='Country') #choices

    def __str__(self):
        return str(self.zip_pin_code) + ', ' + self.locality + ', ' + self.city + '\n'\
               + self.state + ', ' + self.country


class Contact(models.Model):

    website = models.URLField(help_text='Associated Website', null=True, blank=True)

    phone_number = models.CharField(max_length=32, help_text='Phone number')
    mobile_number = models.CharField(max_length=32, help_text='Mobile number', null=True, blank=True)

    # fb, insta, twitter

    def __str__(self):
        return '{0}, {1}\n{2}'.format(self.phone_number, self.mobile_number,
                                           self.website)


class IncomeSource(models.Model):
    name = models.CharField(max_length=64, help_text='Enter income source')

    def __str__(self):
        return self.name


class Facilities(models.Model):
    name = models.CharField(max_length=64,
                            help_text="Enter facilities provided")

    def __str__(self):
        return self.name


class Orphanage(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)

    name = models.CharField(max_length=256, help_text='Name of Orphanage')

    reg_num = models.CharField(max_length=255, help_text='Registration number',unique=True)

    date_estd = models.DateField(null=True, blank=True, help_text='Date of establishment')

    brief_desc = models.TextField(max_length=1024, help_text='Brief description of Orphanage', blank=True)

    address = models.OneToOneField(Address, on_delete=models.SET_NULL, null=True, help_text='Address')
    contact = models.OneToOneField(Contact, on_delete=models.SET_NULL, null=True, help_text='Contact')

    bank_details = models.OneToOneField(BankDetail, on_delete=models.SET_NULL, null=True, blank=True, help_text='Bank details')

    def display_incomesrc(self):
        return ', '.join(income.name for income in self.income_source.all()[:3])

    income_source = models.ManyToManyField(IncomeSource, help_text='Source of Income', blank=True)

    def display_facilities(self):
        return ', '.join(facility.name for facility in self.facilities.all()[:3])

    facilities = models.ManyToManyField(Facilities, help_text='Facilities Available', blank=True)

    display_pic = models.ImageField(upload_to='orphanage_dp/', default='dream_home.gif', help_text='Display picture for orphanage',
                                    null=True, blank=True)

    activated = models.BooleanField('Activated', default=False)

    def __str__(self):
        return '{0}'.format(self.name)

    def get_absolute_url(self):
        return reverse('orphanage-detail', args=[str(self.id)])

    class Meta:
        ordering = ['name', 'date_estd']
    # chairman


class Donor(models.Model):
    first_name = models.CharField(max_length=64, help_text='First Name', blank=True)
    last_name = models.CharField(max_length=64, help_text='Last Name', blank=True)

    date = models.DateTimeField(auto_now_add=True, help_text='Donation date/time')

    phone_number = models.CharField(max_length=32, help_text='Phone number', null=True, blank=True)
    email = models.EmailField(help_text='Email', null=True, blank=True)

    amount_donated = models.FloatField(help_text='Donation Amount')
    payuMoneyId = models.CharField(unique=True, max_length=20, help_text='payu Money ID', null=True)
    donation_remark = models.CharField(max_length=1024, help_text='Donation Remarks', null=True, blank=True)

    donated_to = models.ForeignKey('Orphanage', on_delete=models.CASCADE)

    def __str__(self):
        return '{0} {1}'.format(self.first_name, self.last_name)

    class Meta:
        ordering = ['first_name', 'last_name', 'amount_donated']


def generate_urid():
    year = date.today().year
    month = date.today().month
    day = date.today().day

    last_request = AdoptionRequest.objects.all().order_by('request_id').last()
    if not last_request:
        return 'HOP-' + str(year) + str(month).zfill(2) + str(day).zfill(2) + '000000'

    request_id = last_request.request_id
    request_id_number = int(request_id[12:18])
    request_id_day = int(request_id[10:12])
    request_id_month = int(request_id[8:10])
    request_id_year = int(request_id[4:8])

    print(request_id_day, request_id_month, request_id_year)
    if day != request_id_day:
        request_id_number = 0

    new_request_id_number = request_id_number + 1
    new_request_id = 'HOP-' + str(year) + str(month).zfill(2) + str(day).zfill(2) + \
                     str(new_request_id_number).zfill(6)
    return new_request_id


class AdoptionRequest(models.Model):
    first_name = models.CharField(max_length=64, help_text='First Name')
    last_name = models.CharField(max_length=64, help_text='Last Name')

    request_id = models.CharField(primary_key=True, default=generate_urid,editable=False, max_length=18)

    request_date = models.DateTimeField(auto_now_add=True, help_text='Adoption request date/time')

    dob = models.DateField(help_text='Date of Birth (For age purpose)')
    phone_number = models.CharField(max_length=32, help_text='Phone number')
    mobile_number = models.CharField(max_length=32, blank=True)
    email = models.EmailField(help_text='Email', null=True)
    address = models.OneToOneField(Address, on_delete=models.SET_NULL, help_text='Address', null=True)

    occupation = models.CharField(max_length=64, help_text='Occupation')

    income = models.FloatField(help_text='Annual income')

    MARRIAGE_STATUS = (
        ('m', 'Married'),
        ('u', 'Un-married'),
        ('d', 'Divorced'),
    )

    married = models.CharField(
        max_length=1,
        default='m',
        choices=MARRIAGE_STATUS,
        help_text='Marriage Status'
    )

    family_members = models.IntegerField('Total number of family members')

    requested_for = models.ForeignKey(Orphan, on_delete=models.CASCADE)

    CHOICE = (
        ('a', 'Approved'),
        ('d', 'Declined'),
        ('p', 'Pending'),
    )
    approved = models.CharField(max_length=1, default='p', choices=CHOICE)

    class Meta:
        ordering = ['first_name', 'last_name', 'request_id']

templates/checkout.html
{% extends 'base_generic.html' %}
{#{% block html_tag %}<html lang="en" onload="run_ajax()">{% endblock %}#}
{% block content %}
    <div class="sub-title">
        Donate to {{ orphanage.name }}<span style="display: none" id="orphanage_pk">{{ orphanage.pk }}</span>
    </div>


    <div class="form-wrap-div form_wrap">
        {% if error %}

            <span style="color:red">Please fill all mandatory fields.</span>
            <br/>
            <br/>
        {% endif %}

        <form method="post" name="payuForm">
            {% csrf_token %}
            <input type="hidden" name="key"/>
            <input type="hidden" name="hash_string"/>
            <input type="hidden" name="hash"/>
            <input type="hidden" name="txnid"/>
            <table>
                <tr>
                    <td colspan="2"><input type="text" placeholder="Amount" name="amount" required/></td>
                </tr>
                <tr>
                    <td><input type="text" maxlength="64" placeholder="Firstname" name="firstname" id="firstname"
                               required/></td>
                    <td><input type="text" maxlength="64" placeholder="Lastname" name="lastname" id="lastname"/></td>
                </tr>
                <tr>
                    <td><input type="email" name="email" placeholder="Email" id="email" required/></td>
                    <td><input type="text" maxlength="32" name="phone" placeholder="Phone" required/></td>
                </tr>
                <tr>
                    <td colspan="2"><textarea maxlength="1024" placeholder="Donation Remarks" name="udf2"
                                              required></textarea></td>
                </tr>
                <tr>
                    <td><input type="hidden" name="surl" size="64"/></td>
                    <td><input type="hidden" name="furl" size="64"/></td>
                </tr>

                <tr>
                    <td>
                        <input type="hidden" name="productinfo" value="donation">
                        <input type="hidden" name="service_provider" size="64"/>
                    </td>
                </tr>

                <tr>
                    <td><input type="hidden" name="curl" value=""/></td>
                </tr>
                {#            <tr>#}
                {#                <td>Address1:</td>#}
                {#                <td><input name="address1"/></td>#}
                {#                <td>Address2:</td>#}
                {#                <td><input name="address2"/></td>#}
                {#            </tr>#}
                {#            <tr>#}
                {#                <td>City:</td>#}
                {#                <td><input name="city"/></td>#}
                {#                <td>State:</td>#}
                {#                <td><input name="state"/></td>#}
                {#            </tr>#}
                {#            <tr>#}
                {#                <td>Country:</td>#}
                {#                <td><input name="country"/></td>#}
                {#                <td>Zipcode:</td>#}
                {#                <td><input name="zipcode"/></td>#}
                {#            </tr>#}
                <tr>
                    {#                <td>UDF1:</td>#}
                    <td><input type="hidden" name="udf1"/></td>
                    {#                <td>UDF2:</td>#}
                    {#                <td><input name="udf2"/></td>#}
                </tr>
                {#            <tr>#}
                {#                <td>UDF3:</td>#}
                {#                <td><input name="udf3"/></td>#}
                {#                <td>UDF4:</td>#}
                {#                <td><input name="udf4"/></td>#}
                {#            </tr>#}
                {#            <tr>#}
                {#                <td>UDF5:</td>#}
                {#                <td><input name="udf5"/></td>#}
                {#            </tr>#}
                <tr>
                    <td colspan="2" class="submit-td"><input class="donate-btn" type="submit" value="Donate"></td>
                </tr>
            </table>
        </form>
    </div>

{% endblock %}

templates/contact_us.html
{% extends 'base_generic.html' %}

{% block title %}About Us{% endblock %}
{% block content %}
   <div class="sub-title">
        About Us
    </div>
    <div class="content-central">
        <div class="information-div">Contact us at <a href="mailto:hopefo.staff@gmail.com">Hope for Orphans Staff</a></div>
    </div>
{% endblock %}

templates/donation_failure.html
{% extends 'base_generic.html' %}

{% block content %}
    <div class="content-central">
        <div class="information-div failed">
            {{ failure_data.first_name }}, your donation of
            {{ failure_data.amount_donated }} has unfortunately failed. Please try again.
        </div>
    </div>
{% endblock %}

templates/donation_success.html
{% extends 'base_generic.html' %}

{% block content %}
    <div class="content-central">
        <div class="information-div">
            <span class="info-span">{{ success_data.first_name }}</span>, your donation of <span class="info-span">
            Rs. {{ success_data.amount_donated }}</span> to <span class="info-span">{{ success_data.donated_to.name }}</span>
            has been successful. We hope you'll continue to contribute in the future as well.
        </div>
    </div>
{% endblock %}

templates/donors_list.html
{% extends 'base_generic.html' %}

{% block title %}Donations | Hope For Orphans{% endblock %}

{% block content %}
    <div class="sub-title">
        List of all Donations
        {#        <a class="link-in-subtitle-bar" href="{% url 'add-orphan' %}">Add Orphan</a>#}

    </div>
    <div class="content-central-donation">
        {% if donors %}

            <table class="card-table">
                <tr>
                    <th class="card-table-header">Transaction ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Amount Donated</th>
                    <th>Donation Date</th>
                    <th>Remarks</th>
                </tr>
                {% for donor in donors %}

                    <tr class="card-table-row-donation">
                        <td class="card-cells" id="adopt-req-id">
                            {{ donor.payuMoneyId }}
                        </td>

                        <td class="card-cells">
                            {{ donor.first_name }} {{ donor.last_name }}
                        </td>

                        <td class="card-cells">
                            {{ donor.email }}
                        </td>
                        <td class="card-cells">
                            {{ donor.phone_number }}
                        </td>
                        <td class="card-cells ">
                            {{ donor.amount_donated }}
                        </td>
                        <td class="card-cells ">
                            {{ donor.date }}
                        </td>
                    <td class="card-cells ">
                            {{ donor.donation_remark }}
                        </td>
                    </tr>

                {% endfor %}
            </table>

        {% else %}
            <p style="text-align: center">No donations received yet</p>
        {% endif %}
    </div>

    {% if donors.has_other_pages %}
        <ul class="pagination">
            {% if donors.has_previous %}
                <li><a href="?page={{ donors.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="pagination-disabled"><span>&laquo;</span></li>
            {% endif %}

            {% for i in donors.paginator.page_range %}
                {% if donors.number == i %}
                    <li><span class="pagination-active">{{ i }}</span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if donors.has_next %}
                <li><a href="?page={{ donors.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="pagination-disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}


    <div id="myModal" class="modal">
        <div class="modal-content">
        </div>
    </div>
{% endblock %}

templates/orphan_profile.html
{% extends 'base_generic.html' %}

{% block content %}
    <div class="content-central">
        <table class="image-btn-table">
            <tr>
                <td>
                    <div class="profile-dp-div">
                    <img class="profile-dp"
                     src="{% if orphan.avatar%}
                        {{ orphan.avatar.url }}
                        {% else %}
                        {% load static %}
                        {% static 'orphan-placeholder.jpg' %}
                        {% endif %}" alt="Orphan DP">
                    </div>
                </td>
            </tr>
            <tr>
                <td><a class="link-buttons" href="">Request Adoption</a></td>
            </tr>
            <tr>
                <td><a class="link-buttons" href="">Sponsor</a></td>
            </tr>
        </table>


        <div class="profile-name">
            {{ orphan.first_name}} {{ orphan.last_name}}
        </div>
        <div style="margin: 4px 0"><a class="card-orphanage-link" href="{% url 'profile' %}">{{ orphan.orphanage.name }}</a></div>

        <div class="status-div">{{ orphan.get_status_display }}</div>
{#        <div id="orphanage-desc">#}
{#            {{ orphanage.brief_desc }}#}
{#        </div>#}

        <table class="details-table">
            <th>Details</th>
            <tr>
                <td>Gender: {{ orphan.get_gender_display}}</td>
            </tr>
            <tr>
                <td>DOB: {{ orphan.dob}}</td>
            </tr>
            <tr>
                <td>Education: {{ orphan.education}}</td>
            </tr>
        </table>
{#        <div class="total-don-class" id="total-don-text-div">#}
{#            Total Donation Raised Through This Platform#}
{#        </div>#}
{#        <div class="total-don-class" id="total-don-div">#}
{#            Rs. {{ orphanage.total_donation_raised }}#}
{#        </div>#}
{##}
{#        <div id="table-div">#}
            <table class="details-table">
                <th>Hobbies</th>
                {% for h in orphan.hobbies.all%}
                    <tr>
                        <td>{{ h }}</td>
                    </tr>
                {% endfor %}
            </table>
{#            <table class="details-table" id="income-table">#}
{#                <th>Income Sources</th>#}
{#                {% for i in orphanage.income_source.all%}#}
{#                    <tr>#}
{#                        <td>{{ i }}</td>#}
{#                    </tr>#}
{#                {% endfor %}#}
{#            </table>#}
{#        </div>#}
    </div>
{% endblock %}

templates/orphanages_list.html
{% extends 'base_generic.html' %}

{% block content %}
    <div class="sub-title">
        List of all Orphanages
        {#        <a class="link-in-subtitle-bar" href="{% url 'add-orphan' %}">Add Orphan</a>#}

    </div>
    <div class="content-central">
        {% if orphanages %}
            <div class="list-labels orphanage-list-label">
                <div>Name</div>
                <div>No. of Orphans</div>
            </div>

            {% for orphanage in orphanages %}
                {% if orphanage.activated %}


                <div class="card-div">

                    <div class="dp-div">
                        <img class="orphan-avatar" src="{{ orphanage.display_pic.url }}">
                    </div>

                    <div class="name-div name-div-orphanage">
                        <a class="orphanage-link-list"
                           href="{% url 'orphanage_view' orphanage.pk %}">{{ orphanage.name }}</a>
                        {{ orphanage.address.state }}
                    </div>
                    <div style="align-self: center">
                        {{ orphanage.orphan_set.count }}
                    </div>

                </div>
                {% endif %}
            {% endfor %}

        {% else %}
            <p style="text-align: center">No orphanages added yet</p>
        {% endif %}


    </div>
    {% if orphanages.has_other_pages %}
        <ul class="pagination">
            {% if orphanages.has_previous %}
                <li><a href="?page={{ orphanages.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="pagination-disabled"><span>&laquo;</span></li>
            {% endif %}

            {% for i in orphanages.paginator.page_range %}
                {% if orphanages.number == i %}
                    <li><span class="pagination-active">{{ i }}</span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if orphanages.has_next %}
                <li><a href="?page={{ orphanages.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="pagination-disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

templates/orphans_list.html
{% extends 'base_generic.html' %}

{% block content %}

    <div class="sub-title">
        List of orphans from all Orphanages
        {#        <a class="link-in-subtitle-bar" href="{% url 'add-orphan' %}">Add Orphan</a>#}

    </div>
    <div class="content-central">
        {% if orphans %}
            <div class="list-labels orphans-list-label">
                <div>Name</div>
                <div>Adoption Status</div>
            </div>
            <div class="accordian">
                {% for o in orphans %}
                    <div class="card-div" id="accordian-card">
                        {#                    <div class="dp-div">#}
                        {#                        <img class="orphan-avatar" src="{{ o.avatar.url }}">#}
                        {#                    </div>#}
                        <div class="name-div">
                            <a class="card-orphan-link">{{ o.first_name }} {{ o.last_name }}</a>
                            <a class="card-orphanage-link"
                               href="{% url 'orphanage_view' o.orphanage.pk %}">{{ o.orphanage.name }}</a>
                        </div>
                        <span class="status-span {% if o.status == 'a' %}status-span-green
                                {% elif o.status == 'n' %}status-span-blue{% else %}status-span-black{% endif %}">
                            {{ o.get_status_display }}
                        </span>
                    </div>
                    <div class="card-div-content">
                        <div class="card-div-content-wrapper">
                            <span class="orphans-pk" style="display: none">{{ o.pk }}</span>

                            <div class="age-gender-div">
                                <span class="age-gender-label">Age</span>
                                <span class="age-gender-content">{{ o.calculate_age }}</span>
                            </div>

                            <div class="age-gender-div">
                                <span class="age-gender-label">Gender</span>
                                <span class="age-gender-content">{{ o.get_gender_display }}</span>
                            </div>

                            <div class="card-buttons">
                                {#                                <a class="link-buttons" href="">Sponsor</a>#}
                                {#                                <a class="link-buttons" href="">Adoption Request</a>#}
                                {#                                {% if user.is_authenticated %}#}
                                {#                                    <input class="red-buttons edit-buttons" id="" type="button" value="Edit">#}
                                {#                                    <input class="red-buttons delete-buttons" id="" type="button" value="Delete">#}
                                {#                                {% else %}#}
{#                                <a class="red-buttons" href="">Sponsor</a>#}
                                {% if o.status == 'a' %}
                                    <span class="red-buttons adopt-request">Adoption Request</span>
                                {% endif %}
                                {#                                {% endif %}#}

                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p style="text-align: center">No orphans added yet</p>
        {% endif %}
    </div>

    {% if orphans.has_other_pages %}
{#        <div class="pagination-div">#}
            <ul class="pagination">
                {% if orphans.has_previous %}
                    <li><a href="?page={{ orphans.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="pagination-disabled"><span>&laquo;</span></li>
                {% endif %}

                {% for i in orphans.paginator.page_range %}
                    {% if orphans.number == i %}
                        <li><span class="pagination-active">{{ i }}</span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if orphans.has_next %}
                    <li><a href="?page={{ orphans.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="pagination-disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
{#        </div>#}
    {% endif %}

    <div id="myModal" class="modal">
        <div class="modal-content">
        </div>
    </div>
{% endblock %}

templates/partial_success_adopt_req.html
<div class="modal-header">
    <span>Adoption Request Form</span>

</div>
<div class="modal-body">
    Your request is successfully submitted. Your request id is <span class="request-id"></span>.
    Please wait for the approval of your request from the concerned orphanage,
    you'll be contacted shortly. Thank you.
</div>
<div class="modal-footer">
    <button class="close-button">Close</button>
</div>